apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  selector:
    matchLabels:
      app: app1
      tier: app1
      track: stable
  template:
    metadata:
      labels:
        app: app1
        tier: app1
        track: stable
    spec:
      containers:
        - name: app1
          image: "app1:test"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  type: NodePort
  selector:
    app: app1
    tier: app1
  ports:
  - protocol: TCP
    port: 9000
    targetPort: http
    nodePort: 30000